#! /usr/bin/perl

# Loop over a range of params for udp test

$sender = "cicada2";
$recvr = "east";
$ssh = "ssh -x";
$path = "";

# Open output file
open (S_LOG, ">send.dat") or die "Error opening send.dat\n";
open (R_LOG, ">recv.dat") or die "Error opening recv.dat\n";

# Some header lines
print S_LOG "# Sender: $sender\n";
print S_LOG "# packet_size(B) total_size(MB) rate(MB/s) load recvr\n";
print R_LOG "# Receiver: $recvr\n";
print R_LOG "# packet_size(B) total_size(MB) rate(MB/s) drop_frac load recvr\n";

# for 10gig suffix
$suff = "_10";

# Packet size loop
#for ($ps=1024; $ps<15000; $ps+=256) {
# wait loop
$wt = 0;
while ($wt<1000) {
    $ps = 8192;
    $send_cmd = "udp_send -q -d 10.0 -w $wt -s $ps $recvr$suff";
    $recv_cmd = "udp_recv -q -s $ps $sender$suff";
    print "$send_cmd\n";
    print "$recv_cmd\n";
    open (RR, "ssh $recvr '$recv_cmd'|") or die "Error calling $recv_cmd\n";
    sleep(2); # Wait for udp_recv to start up
    open (SS, "ssh $sender '$send_cmd'|") or die "Error calling $send_cmd\n";
    while (<SS>) { chomp; $send_output=$_; }  close SS;
    while (<RR>) { chomp; $recv_output=$_; }  close RR;
    print S_LOG "$send_output\n";
    print R_LOG "$recv_output\n";
    # Variable wait increment
    if ($wt>300) { $wt += 100; }
    elsif ($wt>100) { $wt += 25; }
    elsif ($wt>50) { $wt += 5; }
    elsif ($wt>20) { $wt += 2; }
    else { $wt += 1; }
}

close S_LOG;
close R_LOG;
